### ISSUE TITLE
Remove enchant shining effect

### ISSUE THREAD

**Issue by ZYFDroid** [innnky/majobroom#4]
just simply add 
```
    @Override
    public boolean hasGlint(ItemStack stack) {
        return false;
        //return super.hasGlint(stack);
    }

```
in BaseArmor.java

**Comment by innnky** [comment]
thank you very much for your help!
（话说大佬你是国人吗，我代码水平很烂（捂脸）本来这个项目只是用来学习fabric和GitHub的使用的，根本没想到还有别人会看到😂）

**Comment by ZYFDroid** [comment]
是的，还有其他几个小问题也改了一下（另外我也是萌新，还没写过任何mod）

**Comment by ZYFDroid** [comment]
我把其他几个issue和pr的说明也改了一下

**Comment by innnky** [comment]
嗯嗯感谢啦

**Comment by innnky** [comment]
github我还不是很会用（捂脸）还得研究研究

**Comment by ZYFDroid** [comment]
可以参考一些国内的开源项目是怎么使用issue和pr的，比如 steamtools （另外记得把我朋友加的私货改回来（合成表，取消自动第三人称））

**Comment by innnky** [comment]
嗯嗯

**Comment by ZYFDroid** [comment]
另外要不要来我朋友的服务器玩玩，模组服（群号433792830）

**Comment by innnky** [comment]
入群的问题怎么这么离谱啊😂
